apiVersion: v1
kind: Service
metadata:
  name: my-demo-app-service
spec:
  selector:
    app: my-demo-app
  ports:
    - nodePort: 31000
      protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort